var cy = cytoscape({

  container: document.getElementById('cy'), // container to render in

  // elements: [ // list of graph elements to start with
  //   {"group":"nodes","data":{"id":"rec0vNdSsnZkIcA4X","parent":"Intervals","name":"Minor 2nd"},"position":{"x":100,"y":100}},
  //   {"group":"nodes","data":{"id":"rec8sFmzq4bUF9g3D","parent":"Intervals","name":"Octave"},"position":{"x":100,"y":1200}},
  //   {"group":"nodes","data":{"id":"recH91UnZq5M46BN2","parent":"Intervals","name":"Perfect 4th"},"position":{"x":100,"y":500}},
  //   {"group":"nodes","data":{"id":"recLsI9cI3dAimpvR","parent":"Intervals","name":"Major 6th"},"position":{"x":100,"y":900}},
  //   {"group":"nodes","data":{"id":"recPcyviOsEepXhnQ","parent":"Intervals","name":"Unison"},"position":{"x":100,"y":0}},
  //   {"group":"nodes","data":{"id":"recS58DmkLKu2grR9","parent":"Intervals","name":"Major 2nd"},"position":{"x":100,"y":200}},
  //   {"group":"nodes","data":{"id":"recZbKFnM0QfVkOmm","parent":"Intervals","name":"Perfect 5th"},"position":{"x":100,"y":700}},
  //   {"group":"nodes","data":{"id":"recdeN9izKLz6FxLx","parent":"Intervals","name":"Minor 3rd"},"position":{"x":100,"y":300}},
  //   {"group":"nodes","data":{"id":"receqRQ6G8fmCtEVx","parent":"Intervals","name":"Tritone"},"position":{"x":100,"y":600}},
  //   {"group":"nodes","data":{"id":"reckvpdIs6Xuq1HVj","parent":"Intervals","name":"Major 3rd"},"position":{"x":100,"y":400}},
  //   {"group":"nodes","data":{"id":"recyMPEnGXy97mxll","parent":"Intervals","name":"Minor 6th"},"position":{"x":100,"y":800}},
  //   {"group":"nodes","data":{"id":"recyyC3ERyaf28Xn6","parent":"Intervals","name":"Major 7th"},"position":{"x":100,"y":1100}},
  //   {"group":"nodes","data":{"id":"reczsYyfXWbFv1v1d","parent":"Intervals","name":"Minor 7th"},"position":{"x":100,"y":1000}},
  //   {"group":"nodes","data":{"id":"rec4lvBafSjpf6iUm","parent":"Shapes","name":"White to Black 9"},"position":{"x":200,"y":900}},
  //   {"group":"nodes","data":{"id":"rec7EU4KfVep7D6Sa","parent":"Shapes","name":"White to Black 7"},"position":{"x":200,"y":700}},
  //   {"group":"nodes","data":{"id":"rec9HUG3nu1eZHs1L","parent":"Shapes","name":"White to White 6"},"position":{"x":200,"y":600}},
  //   {"group":"nodes","data":{"id":"recB9zg5H5TwGtp7e","parent":"Shapes","name":"Black to White 11"},"position":{"x":200,"y":2500}},
  //   {"group":"nodes","data":{"id":"recBe3PY2ElHu4G6x","parent":"Shapes","name":"Black to Black 12"},"position":{"x":200,"y":2600}},
  //   {"group":"nodes","data":{"id":"recBxv0fvY0pkuVkJ","parent":"Shapes","name":"Black to White 7"},"position":{"x":200,"y":2100}},
  //   {"group":"nodes","data":{"id":"recCBGfwxnRisN5v6","parent":"Shapes","name":"White to White 14"},"position":{"x":200,"y":1400}},
  //   {"group":"nodes","data":{"id":"recEVTjwd7ySM8R4J","parent":"Shapes","name":"Black to Black 6"},"position":{"x":200,"y":2000}},
  //   {"group":"nodes","data":{"id":"recG4t1WiOR1DM2tc","parent":"Shapes","name":"White to Black 5"},"position":{"x":200,"y":500}},
  //   {"group":"nodes","data":{"id":"recI4GQgm65zG0mWf","parent":"Shapes","name":"White to White 4"},"position":{"x":200,"y":400}},
  //   {"group":"nodes","data":{"id":"recIhXSA4YZRwrq4w","parent":"Shapes","name":"Black to Black 4"},"position":{"x":200,"y":1800}},
  //   {"group":"nodes","data":{"id":"recOz4xQj9DEV4olt","parent":"Shapes","name":"Black to White 9"},"position":{"x":200,"y":2300}},
  //   {"group":"nodes","data":{"id":"recQVcnBLRQycKSkz","parent":"Shapes","name":"White to White 10"},"position":{"x":200,"y":1000}},
  //   {"group":"nodes","data":{"id":"recVEelstSUtfbWsw","parent":"Shapes","name":"Black to White 3"},"position":{"x":200,"y":1700}},
  //   {"group":"nodes","data":{"id":"recY743bibqUglxhX","parent":"Shapes","name":"White to White 8"},"position":{"x":200,"y":800}},
  //   {"group":"nodes","data":{"id":"reca2z9JHoJ599b0e","parent":"Shapes","name":"White to Black 3"},"position":{"x":200,"y":300}},
  //   {"group":"nodes","data":{"id":"reciaFs54NU3QcW5a","parent":"Shapes","name":"White to Black 13"},"position":{"x":200,"y":1300}},
  //   {"group":"nodes","data":{"id":"reclgFxnI22C1BFhd","parent":"Shapes","name":"Black to White 5"},"position":{"x":200,"y":1900}},
  //   {"group":"nodes","data":{"id":"recpPTjrPCoWEqHqc","parent":"Shapes","name":"Black to White 1"},"position":{"x":200,"y":1500}},
  //   {"group":"nodes","data":{"id":"recppuCcNqM6FkJyH","parent":"Shapes","name":"White to White 12"},"position":{"x":200,"y":1200}},
  //   {"group":"nodes","data":{"id":"recstZnrrXgGG0YOa","parent":"Shapes","name":"Black to Black 2"},"position":{"x":200,"y":1600}},
  //   {"group":"nodes","data":{"id":"rectMuASyozV4jN2j","parent":"Shapes","name":"Black to Black 8"},"position":{"x":200,"y":2200}},
  //   {"group":"nodes","data":{"id":"recuYrPcvwNMSr4Sy","parent":"Shapes","name":"White to White 2"},"position":{"x":200,"y":200}},
  //   {"group":"nodes","data":{"id":"recwYr1BR7SJOhV2K","parent":"Shapes","name":"White to Black 1"},"position":{"x":200,"y":100}},
  //   {"group":"nodes","data":{"id":"recwgjsitkTZuMC7l","parent":"Shapes","name":"White to Black 11"},"position":{"x":200,"y":1100}},
  //   {"group":"nodes","data":{"id":"recwkWJhG5WlEHqAw","parent":"Shapes","name":"Black to Black 14"},"position":{"x":200,"y":2800}},
  //   {"group":"nodes","data":{"id":"recwnb2NblRpgcTQH","parent":"Shapes","name":"Black to White 13"},"position":{"x":200,"y":2700}},
  //   {"group":"nodes","data":{"id":"recxRi3kOFTsWucav","parent":"Shapes","name":"Black to Black 10"},"position":{"x":200,"y":2400}},
  //   {"group":"edges","data":{"id":"rec0JNcCR6mWbIUC4","source":"reckvpdIs6Xuq1HVj","target":"recI4GQgm65zG0mWf"}},
  //   {"group":"edges","data":{"id":"rec0NGLEXI55bl58C","source":"recdeN9izKLz6FxLx","target":"recVEelstSUtfbWsw"}},
  //   {"group":"edges","data":{"id":"rec1ASlwlu2xJo1wR","source":"rec0vNdSsnZkIcA4X","target":"recpPTjrPCoWEqHqc"}},
  //   {"group":"edges","data":{"id":"rec1IKaza0cMlDGGU","source":"rec0vNdSsnZkIcA4X","target":"recwYr1BR7SJOhV2K"}},
  //   {"group":"edges","data":{"id":"rec1TjZXu5iXahNKc","source":"recyyC3ERyaf28Xn6","target":"reciaFs54NU3QcW5a"}},
  //   {"group":"edges","data":{"id":"rec27JwtK79KBBrVe","source":"reczsYyfXWbFv1v1d","target":"recBe3PY2ElHu4G6x"}},
  //   {"group":"edges","data":{"id":"rec2DLayIjgYHioWi","source":"recH91UnZq5M46BN2","target":"rec9HUG3nu1eZHs1L"}},
  //   {"group":"edges","data":{"id":"rec2LQtgpZT0IJ4GP","source":"recS58DmkLKu2grR9","target":"recuYrPcvwNMSr4Sy"}},
  //   {"group":"edges","data":{"id":"rec2WnLuWLHPQLD3E","source":"rec8sFmzq4bUF9g3D","target":"recCBGfwxnRisN5v6"}},
  //   {"group":"edges","data":{"id":"rec2bt9z4VTUpREmG","source":"recH91UnZq5M46BN2","target":"recEVTjwd7ySM8R4J"}},
  //   {"group":"edges","data":{"id":"rec2qRiPJ53ZxGJaX","source":"reczsYyfXWbFv1v1d","target":"recppuCcNqM6FkJyH"}},
  //   {"group":"edges","data":{"id":"rec2wrbmyEGPQ2ABu","source":"recS58DmkLKu2grR9","target":"reca2z9JHoJ599b0e"}},
  //   {"group":"edges","data":{"id":"rec30eWMOr9Ch6X6I","source":"recyyC3ERyaf28Xn6","target":"reciaFs54NU3QcW5a"}},
  //   {"group":"edges","data":{"id":"rec3TXoucMsTcZoqy","source":"recdeN9izKLz6FxLx","target":"recI4GQgm65zG0mWf"}},
  //   {"group":"edges","data":{"id":"rec3UlAkrZF6VIsh0","source":"recyyC3ERyaf28Xn6","target":"reciaFs54NU3QcW5a"}},
  //   {"group":"edges","data":{"id":"rec3opKSqxKwpdERy","source":"reckvpdIs6Xuq1HVj","target":"reclgFxnI22C1BFhd"}},
  //   {"group":"edges","data":{"id":"rec401te35nkXLg1D","source":"recS58DmkLKu2grR9","target":"recuYrPcvwNMSr4Sy"}},
  //   {"group":"edges","data":{"id":"rec4xxwmMzBuere10","source":"rec0vNdSsnZkIcA4X","target":"recpPTjrPCoWEqHqc"}},
  //   {"group":"edges","data":{"id":"rec6SH7qkxJuXmN6C","source":"recyyC3ERyaf28Xn6","target":"reciaFs54NU3QcW5a"}},
  //   {"group":"edges","data":{"id":"rec6lJJCtSj5tcE1w","source":"recZbKFnM0QfVkOmm","target":"recY743bibqUglxhX"}},
  //   {"group":"edges","data":{"id":"rec6uqSakNTVMIvTk","source":"recZbKFnM0QfVkOmm","target":"recBxv0fvY0pkuVkJ"}},
  //   {"group":"edges","data":{"id":"rec71wOlX28VSsdFv","source":"recLsI9cI3dAimpvR","target":"recwgjsitkTZuMC7l"}},
  //   {"group":"edges","data":{"id":"rec7LEyT0Fl4auM9w","source":"rec0vNdSsnZkIcA4X","target":"recwYr1BR7SJOhV2K"}},
  //   {"group":"edges","data":{"id":"rec7kZFoLjSI5eCzh","source":"recdeN9izKLz6FxLx","target":"reca2z9JHoJ599b0e"}},
  //   {"group":"edges","data":{"id":"rec7oyWn0mVKM2Y2t","source":"reckvpdIs6Xuq1HVj","target":"recI4GQgm65zG0mWf"}},
  //   {"group":"edges","data":{"id":"rec7xjLnAKzN6ERew","source":"recLsI9cI3dAimpvR","target":"recB9zg5H5TwGtp7e"}},
  //   {"group":"edges","data":{"id":"rec8Pl85i9cHw1her","source":"recyMPEnGXy97mxll","target":"recQVcnBLRQycKSkz"}},
  //   {"group":"edges","data":{"id":"rec8tiR9mpfliSSlm","source":"recH91UnZq5M46BN2","target":"recEVTjwd7ySM8R4J"}},
  //   {"group":"edges","data":{"id":"rec9D2aCRZvPNiKeH","source":"receqRQ6G8fmCtEVx","target":"recBxv0fvY0pkuVkJ"}},
  //   {"group":"edges","data":{"id":"rec9NeSpmujJBPN1r","source":"rec0vNdSsnZkIcA4X","target":"recuYrPcvwNMSr4Sy"}},
  //   {"group":"edges","data":{"id":"rec9Pb5y4ojummE7V","source":"rec8sFmzq4bUF9g3D","target":"recwkWJhG5WlEHqAw"}},
  //   {"group":"edges","data":{"id":"rec9gSIoTxbzMmaGd","source":"rec8sFmzq4bUF9g3D","target":"recCBGfwxnRisN5v6"}},
  //   {"group":"edges","data":{"id":"rec9rLBZHaHadksgE","source":"recyyC3ERyaf28Xn6","target":"recwnb2NblRpgcTQH"}},
  //   {"group":"edges","data":{"id":"recAbVrmshklqkdmX","source":"rec0vNdSsnZkIcA4X","target":"recpPTjrPCoWEqHqc"}},
  //   {"group":"edges","data":{"id":"recAiP9sQ1OfNqnjH","source":"recdeN9izKLz6FxLx","target":"recIhXSA4YZRwrq4w"}},
  //   {"group":"edges","data":{"id":"recC2S8zaiqZEoCET","source":"recH91UnZq5M46BN2","target":"rec9HUG3nu1eZHs1L"}},
  //   {"group":"edges","data":{"id":"recCMqdXGRrtSVDKM","source":"reczsYyfXWbFv1v1d","target":"recwgjsitkTZuMC7l"}},
  //   {"group":"edges","data":{"id":"recCvRVejxOguooa1","source":"recZbKFnM0QfVkOmm","target":"rec4lvBafSjpf6iUm"}},
  //   {"group":"edges","data":{"id":"recD3FwTnzWFIaQWB","source":"recZbKFnM0QfVkOmm","target":"recY743bibqUglxhX"}},
  //   {"group":"edges","data":{"id":"recDAqOhrcCphwPs4","source":"rec8sFmzq4bUF9g3D","target":"recCBGfwxnRisN5v6"}},
  //   {"group":"edges","data":{"id":"recDFRRmdELPmOLCj","source":"recH91UnZq5M46BN2","target":"rec9HUG3nu1eZHs1L"}},
  //   {"group":"edges","data":{"id":"recDapVV8BqFSv6yn","source":"recS58DmkLKu2grR9","target":"recuYrPcvwNMSr4Sy"}},
  //   {"group":"edges","data":{"id":"recDhFVp2sfNPUgMu","source":"reczsYyfXWbFv1v1d","target":"recBe3PY2ElHu4G6x"}},
  //   {"group":"edges","data":{"id":"recDm306cWWKenTlK","source":"reczsYyfXWbFv1v1d","target":"recB9zg5H5TwGtp7e"}},
  //   {"group":"edges","data":{"id":"recEdeBYJrCTtSrGS","source":"reckvpdIs6Xuq1HVj","target":"recG4t1WiOR1DM2tc"}},
  //   {"group":"edges","data":{"id":"recFIiI9Gdv0dXfmm","source":"recH91UnZq5M46BN2","target":"recEVTjwd7ySM8R4J"}},
  //   {"group":"edges","data":{"id":"recFOTEI0B9MlLOIz","source":"rec0vNdSsnZkIcA4X","target":"recwYr1BR7SJOhV2K"}},
  //   {"group":"edges","data":{"id":"recFd7U8zl444cmz4","source":"reckvpdIs6Xuq1HVj","target":"reclgFxnI22C1BFhd"}},
  //   {"group":"edges","data":{"id":"recGHvYRCfYYgqj3x","source":"recS58DmkLKu2grR9","target":"recuYrPcvwNMSr4Sy"}},
  //   {"group":"edges","data":{"id":"recHBsCdY6IidbRce","source":"recH91UnZq5M46BN2","target":"rec9HUG3nu1eZHs1L"}},
  //   {"group":"edges","data":{"id":"recHP57nEp0j32nHw","source":"recyMPEnGXy97mxll","target":"recOz4xQj9DEV4olt"}},
  //   {"group":"edges","data":{"id":"recHYEwysBnG40GQ6","source":"recyMPEnGXy97mxll","target":"rec4lvBafSjpf6iUm"}},
  //   {"group":"edges","data":{"id":"recHblcFf52hSGZb0","source":"recLsI9cI3dAimpvR","target":"recB9zg5H5TwGtp7e"}},
  //   {"group":"edges","data":{"id":"recHti27LvoBVugSe","source":"recS58DmkLKu2grR9","target":"reca2z9JHoJ599b0e"}},
  //   {"group":"edges","data":{"id":"recHuaWFTH0OmFEzN","source":"recdeN9izKLz6FxLx","target":"recI4GQgm65zG0mWf"}},
  //   {"group":"edges","data":{"id":"recIdqwXdcTBctx1v","source":"recdeN9izKLz6FxLx","target":"recVEelstSUtfbWsw"}},
  //   {"group":"edges","data":{"id":"recIkfA7Nh5jSvbvP","source":"recyMPEnGXy97mxll","target":"recOz4xQj9DEV4olt"}},
  //   {"group":"edges","data":{"id":"recJUvMHN2BSmQYmT","source":"recS58DmkLKu2grR9","target":"recVEelstSUtfbWsw"}},
  //   {"group":"edges","data":{"id":"recJkyrSDnr5cJuhG","source":"recdeN9izKLz6FxLx","target":"recI4GQgm65zG0mWf"}},
  //   {"group":"edges","data":{"id":"recJv9kMZ2Ug2R63d","source":"recyyC3ERyaf28Xn6","target":"recppuCcNqM6FkJyH"}},
  //   {"group":"edges","data":{"id":"recKz1qRZltZcgGyD","source":"rec8sFmzq4bUF9g3D","target":"recwkWJhG5WlEHqAw"}},
  //   {"group":"edges","data":{"id":"recMxqv6u6ex0PF9J","source":"recS58DmkLKu2grR9","target":"recstZnrrXgGG0YOa"}},
  //   {"group":"edges","data":{"id":"recPOuOv4OGzh4aJx","source":"recZbKFnM0QfVkOmm","target":"rectMuASyozV4jN2j"}},
  //   {"group":"edges","data":{"id":"recPjd4QK2jmaDWTw","source":"recS58DmkLKu2grR9","target":"recVEelstSUtfbWsw"}},
  //   {"group":"edges","data":{"id":"recQKOKGRQpV7Up8W","source":"receqRQ6G8fmCtEVx","target":"recY743bibqUglxhX"}},
  //   {"group":"edges","data":{"id":"recQXEhDbATJHsrx9","source":"rec8sFmzq4bUF9g3D","target":"recCBGfwxnRisN5v6"}},
  //   {"group":"edges","data":{"id":"recRHQ4M8aHHDkvM6","source":"recdeN9izKLz6FxLx","target":"recVEelstSUtfbWsw"}},
  //   {"group":"edges","data":{"id":"recRiupCmca54VGmy","source":"recyyC3ERyaf28Xn6","target":"reciaFs54NU3QcW5a"}},
  //   {"group":"edges","data":{"id":"recSktz1TjopZEFgX","source":"recyMPEnGXy97mxll","target":"recOz4xQj9DEV4olt"}},
  //   {"group":"edges","data":{"id":"recT9pKwusQFqvL9S","source":"recdeN9izKLz6FxLx","target":"reca2z9JHoJ599b0e"}},
  //   {"group":"edges","data":{"id":"recTTu2966vs0S8Iu","source":"recZbKFnM0QfVkOmm","target":"recY743bibqUglxhX"}},
  //   {"group":"edges","data":{"id":"recTjNFj8DUxXwECR","source":"reckvpdIs6Xuq1HVj","target":"recI4GQgm65zG0mWf"}},
  //   {"group":"edges","data":{"id":"recTuwL9rjG5MOLWc","source":"recLsI9cI3dAimpvR","target":"recQVcnBLRQycKSkz"}},
  //   {"group":"edges","data":{"id":"recVCGiZV9sS3WEcY","source":"rec0vNdSsnZkIcA4X","target":"recpPTjrPCoWEqHqc"}},
  //   {"group":"edges","data":{"id":"recVvb9a4z5YVqfL7","source":"receqRQ6G8fmCtEVx","target":"rec7EU4KfVep7D6Sa"}},
  //   {"group":"edges","data":{"id":"recW9WAyQjZaW6NWk","source":"receqRQ6G8fmCtEVx","target":"recBxv0fvY0pkuVkJ"}},
  //   {"group":"edges","data":{"id":"recWFm8nBZYge4MO5","source":"recyyC3ERyaf28Xn6","target":"recppuCcNqM6FkJyH"}},
  //   {"group":"edges","data":{"id":"recWHHNp1A09yiq8l","source":"reckvpdIs6Xuq1HVj","target":"recG4t1WiOR1DM2tc"}},
  //   {"group":"edges","data":{"id":"recWIFwvG8YyqnnEU","source":"receqRQ6G8fmCtEVx","target":"recBxv0fvY0pkuVkJ"}},
  //   {"group":"edges","data":{"id":"recWZ1V3bs1zwETvJ","source":"recyMPEnGXy97mxll","target":"recQVcnBLRQycKSkz"}},
  //   {"group":"edges","data":{"id":"recX4VYUckHATyr0s","source":"receqRQ6G8fmCtEVx","target":"recBxv0fvY0pkuVkJ"}},
  //   {"group":"edges","data":{"id":"recXhm1lvxbQzWj95","source":"reczsYyfXWbFv1v1d","target":"recwgjsitkTZuMC7l"}},
  //   {"group":"edges","data":{"id":"recXscDwApi8UJn8t","source":"recyMPEnGXy97mxll","target":"rec4lvBafSjpf6iUm"}},
  //   {"group":"edges","data":{"id":"recY6UkWUCvDyu39i","source":"reczsYyfXWbFv1v1d","target":"recppuCcNqM6FkJyH"}},
  //   {"group":"edges","data":{"id":"recZdh9OwQnZAF5ow","source":"receqRQ6G8fmCtEVx","target":"rec7EU4KfVep7D6Sa"}},
  //   {"group":"edges","data":{"id":"recZk3DXNaT1nay0G","source":"reczsYyfXWbFv1v1d","target":"recppuCcNqM6FkJyH"}},
  //   {"group":"edges","data":{"id":"recb0BWVzVehwzp16","source":"receqRQ6G8fmCtEVx","target":"recBxv0fvY0pkuVkJ"}},
  //   {"group":"edges","data":{"id":"recby1jhrROjw46Ze","source":"recLsI9cI3dAimpvR","target":"recQVcnBLRQycKSkz"}},
  //   {"group":"edges","data":{"id":"reccCZRPBMDg50TSF","source":"rec0vNdSsnZkIcA4X","target":"recuYrPcvwNMSr4Sy"}},
  //   {"group":"edges","data":{"id":"reccEsGsIBQSPdXlo","source":"recZbKFnM0QfVkOmm","target":"rectMuASyozV4jN2j"}},
  //   {"group":"edges","data":{"id":"reccFy4slg18Z61oz","source":"receqRQ6G8fmCtEVx","target":"rec7EU4KfVep7D6Sa"}},
  //   {"group":"edges","data":{"id":"recckiG7WGoZpBeSu","source":"reczsYyfXWbFv1v1d","target":"recB9zg5H5TwGtp7e"}},
  //   {"group":"edges","data":{"id":"recdBrpFmroN6uV5b","source":"rec0vNdSsnZkIcA4X","target":"recwYr1BR7SJOhV2K"}},
  //   {"group":"edges","data":{"id":"recdSL7pjzSvYcFvY","source":"recLsI9cI3dAimpvR","target":"recQVcnBLRQycKSkz"}},
  //   {"group":"edges","data":{"id":"receWX5Xzrv9GX4yx","source":"recH91UnZq5M46BN2","target":"recG4t1WiOR1DM2tc"}},
  //   {"group":"edges","data":{"id":"receeR1Vv79RMyO5f","source":"recZbKFnM0QfVkOmm","target":"recY743bibqUglxhX"}},
  //   {"group":"edges","data":{"id":"recf6icMedQWHlOvB","source":"recZbKFnM0QfVkOmm","target":"recY743bibqUglxhX"}},
  //   {"group":"edges","data":{"id":"recfgUobEeH9wBIPJ","source":"recH91UnZq5M46BN2","target":"recEVTjwd7ySM8R4J"}},
  //   {"group":"edges","data":{"id":"recfv6Xd5egMkvDk1","source":"recLsI9cI3dAimpvR","target":"recB9zg5H5TwGtp7e"}},
  //   {"group":"edges","data":{"id":"recg0crWiKD1V9XwY","source":"recyMPEnGXy97mxll","target":"rec4lvBafSjpf6iUm"}},
  //   {"group":"edges","data":{"id":"recgico7QVGqgdiGW","source":"rec0vNdSsnZkIcA4X","target":"recwYr1BR7SJOhV2K"}},
  //   {"group":"edges","data":{"id":"recgjprZY1kzrMqDD","source":"recZbKFnM0QfVkOmm","target":"rectMuASyozV4jN2j"}},
  //   {"group":"edges","data":{"id":"rechcdD3ghsIUKijs","source":"receqRQ6G8fmCtEVx","target":"rec7EU4KfVep7D6Sa"}},
  //   {"group":"edges","data":{"id":"reciaZjG40NBIlVbn","source":"reczsYyfXWbFv1v1d","target":"recppuCcNqM6FkJyH"}},
  //   {"group":"edges","data":{"id":"reciucSFRbrOCm3Hh","source":"recZbKFnM0QfVkOmm","target":"recY743bibqUglxhX"}},
  //   {"group":"edges","data":{"id":"recix4kXx9OE91MSH","source":"reckvpdIs6Xuq1HVj","target":"recG4t1WiOR1DM2tc"}},
  //   {"group":"edges","data":{"id":"recjhpl1P1jwHUx8G","source":"recLsI9cI3dAimpvR","target":"recxRi3kOFTsWucav"}},
  //   {"group":"edges","data":{"id":"recjiaKPP87ZHygut","source":"rec8sFmzq4bUF9g3D","target":"recCBGfwxnRisN5v6"}},
  //   {"group":"edges","data":{"id":"reck25hyxlFCCNk2b","source":"reckvpdIs6Xuq1HVj","target":"reclgFxnI22C1BFhd"}},
  //   {"group":"edges","data":{"id":"reck34jbl2Lq2sXNb","source":"recdeN9izKLz6FxLx","target":"recIhXSA4YZRwrq4w"}},
  //   {"group":"edges","data":{"id":"reclCYLg0WLO7tSQz","source":"recyyC3ERyaf28Xn6","target":"recwnb2NblRpgcTQH"}},
  //   {"group":"edges","data":{"id":"reclF6qrnRrUQ9OS1","source":"recH91UnZq5M46BN2","target":"rec9HUG3nu1eZHs1L"}},
  //   {"group":"edges","data":{"id":"reclYEqFhAvXiSbnW","source":"rec0vNdSsnZkIcA4X","target":"recpPTjrPCoWEqHqc"}},
  //   {"group":"edges","data":{"id":"reclgfMJNoAUk9jDl","source":"reckvpdIs6Xuq1HVj","target":"reclgFxnI22C1BFhd"}},
  //   {"group":"edges","data":{"id":"recmQZn2WOYOOy76Y","source":"recyMPEnGXy97mxll","target":"rec4lvBafSjpf6iUm"}},
  //   {"group":"edges","data":{"id":"recmVgISpv5xEUxYo","source":"reckvpdIs6Xuq1HVj","target":"recIhXSA4YZRwrq4w"}},
  //   {"group":"edges","data":{"id":"recmm6SJBXVLweQCS","source":"recyyC3ERyaf28Xn6","target":"recwnb2NblRpgcTQH"}},
  //   {"group":"edges","data":{"id":"recn3LgJHFeBkX4GC","source":"recyyC3ERyaf28Xn6","target":"recwnb2NblRpgcTQH"}},
  //   {"group":"edges","data":{"id":"recnGuy9j0eoESVoM","source":"reczsYyfXWbFv1v1d","target":"recppuCcNqM6FkJyH"}},
  //   {"group":"edges","data":{"id":"recoT2DxoIXLPo477","source":"recS58DmkLKu2grR9","target":"recstZnrrXgGG0YOa"}},
  //   {"group":"edges","data":{"id":"recox8P46B4miJiXP","source":"recZbKFnM0QfVkOmm","target":"rectMuASyozV4jN2j"}},
  //   {"group":"edges","data":{"id":"recpCWTHbNurTsQnI","source":"recLsI9cI3dAimpvR","target":"recQVcnBLRQycKSkz"}},
  //   {"group":"edges","data":{"id":"recpIeg2vBW8a74L5","source":"recyMPEnGXy97mxll","target":"recxRi3kOFTsWucav"}},
  //   {"group":"edges","data":{"id":"recpjg1P94uUpiagZ","source":"recLsI9cI3dAimpvR","target":"recwgjsitkTZuMC7l"}},
  //   {"group":"edges","data":{"id":"recqZ00c6Ga0P4OnI","source":"recyMPEnGXy97mxll","target":"recQVcnBLRQycKSkz"}},
  //   {"group":"edges","data":{"id":"recr5jSHvk9xskusY","source":"reckvpdIs6Xuq1HVj","target":"recG4t1WiOR1DM2tc"}},
  //   {"group":"edges","data":{"id":"recsM28i8kCF1CGbE","source":"recH91UnZq5M46BN2","target":"reclgFxnI22C1BFhd"}},
  //   {"group":"edges","data":{"id":"rectJf1YWph3ch1H8","source":"recLsI9cI3dAimpvR","target":"recwgjsitkTZuMC7l"}},
  //   {"group":"edges","data":{"id":"recv6E6bQXQs36Rjs","source":"rec8sFmzq4bUF9g3D","target":"recwkWJhG5WlEHqAw"}},
  //   {"group":"edges","data":{"id":"recvALfFzZXPrG8z3","source":"rec8sFmzq4bUF9g3D","target":"recCBGfwxnRisN5v6"}},
  //   {"group":"edges","data":{"id":"recvEXdfZBNgTL8i3","source":"rec8sFmzq4bUF9g3D","target":"recwkWJhG5WlEHqAw"}},
  //   {"group":"edges","data":{"id":"recvnPoekFhRKTluh","source":"receqRQ6G8fmCtEVx","target":"recY743bibqUglxhX"}},
  //   {"group":"edges","data":{"id":"recvwRgIwgHryPLso","source":"recyMPEnGXy97mxll","target":"recOz4xQj9DEV4olt"}},
  //   {"group":"edges","data":{"id":"recwJBm5MkaiHZkbh","source":"recH91UnZq5M46BN2","target":"rec9HUG3nu1eZHs1L"}},
  //   {"group":"edges","data":{"id":"recwSsIkK7NuLTKjE","source":"rec8sFmzq4bUF9g3D","target":"recwkWJhG5WlEHqAw"}},
  //   {"group":"edges","data":{"id":"recwq6mOvpjTjkmce","source":"reczsYyfXWbFv1v1d","target":"recBe3PY2ElHu4G6x"}},
  //   {"group":"edges","data":{"id":"recxNuUhEhtW4N0Cj","source":"recLsI9cI3dAimpvR","target":"recxRi3kOFTsWucav"}},
  //   {"group":"edges","data":{"id":"recxfv00f9IltCyid","source":"receqRQ6G8fmCtEVx","target":"rec7EU4KfVep7D6Sa"}},
  //   {"group":"edges","data":{"id":"recxyZhUuTLGqUkx3","source":"recdeN9izKLz6FxLx","target":"reca2z9JHoJ599b0e"}},
  //   {"group":"edges","data":{"id":"recyAOe9qzA62elMr","source":"recyyC3ERyaf28Xn6","target":"recwnb2NblRpgcTQH"}},
  //   {"group":"edges","data":{"id":"recyaPumcRLvHm2X8","source":"recS58DmkLKu2grR9","target":"recstZnrrXgGG0YOa"}},
  //   {"group":"edges","data":{"id":"recyao4HEznFyCWhQ","source":"rec8sFmzq4bUF9g3D","target":"recCBGfwxnRisN5v6"}},
  //   {"group":"edges","data":{"id":"reczIkEQFj72Xt7dL","source":"recdeN9izKLz6FxLx","target":"recI4GQgm65zG0mWf"}},
  //   {"group":"edges","data":{"id":"reczT8ap88cwym1gi","source":"recS58DmkLKu2grR9","target":"recuYrPcvwNMSr4Sy"}} 
  // ],

  elements: elements_json,

  // style: [
  //   {
  //     selector: 'node',
  //     style: {
  //       'content': 'data(name)'
  //     }
  //   },
  //   {
  //     selector: 'edge',
  //     style: {
  //       'width': 3,
  //       'line-color': '#ccc',
  //       'target-arrow-color': '#ccc',
  //       'target-arrow-shape': 'triangle'
  //     }
  //   }
  // ],


  style: [ // the stylesheet for the graph
    {
      selector: 'node',
      style: {
        'background-color': '#666',
        'label': 'data(name)',
        'text-valign': 'bottom',
      }
    },

    {
      selector: 'edge',
      style: {
        'width': 'data(weight)',
        // 'line-color': '#ccc',
      }
    },
    {
      selector: 'label',
      style: {
        'text-valign': "top",
      }
    }
  ],

  // style: cytoscape.stylesheet()
  //   .selector('node')
  //     .style({
  //       'text-valign': function(ele) {
  //         console.log(ele.data("parent") == "Intervals" ? "top" : "bottom");
  //         console.log(ele.data("Parent"));
  //         return ele.data("parent") == "Intervals" ? "top" : "bottom";
  //       }
  //     }),




  layout: {
    name: 'preset',
  },

  // minZoom: 1e-50,
  // maxZoom: 1e50,
  zoomingEnabled: true,
  userZoomingEnabled: false,
  panningEnabled: true,
  userPanningEnabled: true,
  boxSelectionEnabled: false,
  selectionType: 'single',
  touchTapThreshold: 8,
  desktopTapThreshold: 4,
  autolock: true,
  autoungrabify: false,
  autounselectify: false,

});

